# Commands to start on workspace startup
tasks:
  - init: npm install
    command: npm run dev
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
#  - port: 3001
#    onOpen: ignore
