name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install and Build for GitHub Pages
        run: |
          npm ci
          npm run build
        env:
          ELEVENTY_ENV: production
          BASE_URL: "https://digitallatin.org/"
          PATH_PREFIX: "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site